// EXPECT-ERROR: not both
// 3.0: CSP4CMSIS_DYNAMIC_ALLOCATION and CSP4CMSIS_STATIC_ALLOCATION exclude each other.
#ifndef CSP4CMSIS_STATIC_ALLOCATION
#define CSP4CMSIS_STATIC_ALLOCATION 1
#endif
#define CSP4CMSIS_DYNAMIC_ALLOCATION 1
#include "csp/csp4cmsis.h"
